api.joke_random :
    path     : /
    methods  : GET
    defaults :
        _controller: \Chuck\App\Api\Controller\JokesController::indexAction

api.get_joke :
    path     : /{id}
    methods  : GET
    defaults :
        _controller : \Chuck\App\Api\Controller\JokesController::getAction

api.joke_slack :
    path     : /slack
    methods  : GET
    defaults :
        _controller: \Chuck\App\Api\Controller\JokesController::slackAction
