api.joke_random :
    path     : /random
    methods  : GET
    defaults :
        _controller: \Chuck\App\Api\Controller\JokesController::randomAction

api.joke_slack :
    path     : /slack
    methods  : [ GET, POST ]
    defaults :
        _controller: \Chuck\App\Api\Controller\JokesController::slackAction
        
api.get_joke :
    path     : /{id}
    methods  : GET
    defaults :
        _controller : \Chuck\App\Api\Controller\JokesController::getAction
