api.jokes_random :
    path     : /
    methods  : GET
    defaults :
        _controller: \Chuck\App\Api\Controller\JokesController::indexAction
    schemes:  [https]

api.jokes_slack :
    path     : /slack
    methods  : GET
    defaults :
        _controller: \Chuck\App\Api\Controller\JokesController::slackAction
    schemes:  [https]
