api :
    path     : /
    methods  : GET
    defaults :
        _controller: \Chuck\App\Api\Controller\IndexController::indexAction

api.slack :
    path     : /slack
    methods  : GET
    defaults :
        _controller: \Chuck\App\Api\Controller\IndexController::slackAction
