api :
    path     : /
    methods  : GET
    defaults :
        _controller: \Chuck\App\Api\Controller\IndexController::indexAction
    schemes:  [https]

jokes:
    prefix    : /jokes/
    resource  : routes/jokes.yml
