api :
    path     : /
    methods  : GET
    defaults :
        _controller : \Chuck\App\Api\Controller\IndexController::indexAction

api.categories :
    path     : /categories
    methods  : GET
    defaults :
        _controller : \Chuck\App\Api\Controller\CategoriesController::indexAction
        
connect:
    prefix   : /connect/
    resource : routes/connect.yml

jokes:
    prefix   : /jokes/
    resource : routes/jokes.yml

sitemap.index :
    path      : /sitemaps/index.xml
    methods   : GET
    defaults  :
        _controller : \Chuck\App\Api\Controller\SitemapController::indexAction

sitemap.jokes :
    path      : /sitemaps/jokes-{page}.xml
    methods   : GET
    defaults  :
        _controller : \Chuck\App\Api\Controller\SitemapController::jokesAction